name: Build on mingw

on:
  push:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-mingw.yml'
      - 'xmake.lua' 
  pull_request:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-mingw.yml'
      - 'xmake.lua' 
  workflow_dispatch:

jobs:
  linuxbuild:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y cmake g++-mingw-w64-x86-64 wine
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      # Force xmake to a specific folder (for cache)
      - name: Set xmake global dir
        run: |
          echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/.xmake-global" >> "${{ github.env }}"
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.1
      - name: update repo
        run: xmake repo -u
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
            ${{ github.workspace }}/build/.build_cache
          key: ${{ runner.os }}-xmake-qt-${{ hashFiles('**/xmake.lua') }}
      - name: config
        run: xmake config --yes -vD --plat=mingw
      - name: build
        run: xmake build --yes -vD
      - name: test
        run: xmake run --yes -vD --diagnosis --group=tests
  windowsbuild:
    runs-on: windows-2019
    steps:
      - name: Run the installer as administrator
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
      - name: Scoop Path
        run: |
          echo "C:\Users\runneradmin\scoop\shims" > $Env:GITHUB_PATH
      - name: Install dependencies
        run: |
          scoop install main/make
          scoop install main/mingw
          scoop install main/cmake
          scoop install main/uutils-coreutils
          scoop install main/elvish
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.1
      - name: update repo
        run: |
          xrepo update-repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: config
        run: elvish bin/config.elv
      - name: build
        run: elvish bin/build.elv
      - name: test
        run: elvish bin/test.elv
