name: Build on mingw

on:
  push:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'lolly/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-mingw.yml'
      - 'xmake.lua' 
      - 'bin/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Kernel/**'
      - 'System/**'
      - 'lolly/**'
      - 'tests/**'
      - '.github/workflows/ci-xmake-mingw.yml'
      - 'xmake.lua' 
      - 'bin/**'
  workflow_dispatch:

jobs:
  linuxbuild:
    if: false # disable it for cpr
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y cmake g++-mingw-w64-x86-64 wine
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      # Force xmake to a specific folder (for cache)
      - name: Set xmake global dir
        run: |
          echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/.xmake-global" >> "${{ github.env }}"
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.7
      - name: update repo
        run: xmake repo -u
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
            ${{ github.workspace }}/build/.build_cache
          key: ${{ runner.os }}-xmake-qt-${{ hashFiles('**/xmake.lua') }}
      - name: config
        run: xmake config --yes -vD --plat=mingw --enable_tests=true
      - name: build
        run: xmake build --yes -vD
      - name: test
        run: xmake run --yes -vD --diagnosis --group=tests
  windowsbuild:
    if: false # disable it for cpr, we may need to upgrade mingw later
    runs-on: windows-2019
    env:
      # Force xmake to a specific folder (for cache)
      XMAKE_GLOBALDIR: "${{ github.workspace }}\\.xmake-global"
    steps:
      - uses: elves/setup-elvish@v1
        with:
          elvish-version: 0.19.2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.7
      - name: update repo
        run: |
          xrepo update-repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache packages from xrepo
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ runner.os }}-xrepo-${{ hashFiles('**/xmake.lua') }}
      - name: config
        run: elvish bin/config_mingw
      - name: build
        run: xmake build --yes -vD --all
      - name: test
        run: xmake run --yes -vD --group=tests
      - name: benchmark
        run: xmake run --yes --group=bench
